### ISSUE TITLE
is there any documentation exist for consuming this api 

### ISSUE THREAD

**Issue by aman-saggu-git** [HiznyakNikita/facebook-messenger-net-lib#1]
is there any documentation exist for information regarding using this api . if i use sendmessage like below it is not posting message . my token is page token i have generated from graph api explorer tools

```
MessengerAPI obj = new MessengerAPI("MyPageTojen");
obj.SendTextMessageAsync(660746514005471, "Hello");
```

**Comment by mkh-dev-444** [comment]
Documentation is in development. Now the example of consuming this api you can see at:
https://github.com/HiznyakNikita/social-pools-blocks

**Comment by aman-saggu-git** [comment]
@HiznyakNikita I could not find code files there is only assembly file over there. Is that enough

**Comment by mkh-dev-444** [comment]
@bhallaheemanshu You can find code files in develop branch

**Comment by mkh-dev-444** [comment]
@bhallaheemanshu [Here](https://github.com/HiznyakNikita/facebook-messenger-net-lib/wiki) you an see docs to c# api
